// ===== MARKETPLACE (delivery app público estilo iFood) =====

export interface MarketDish {
  id: string
  name: string
  description: string
  price: number
  oldPrice?: number
  emoji: string
  category: string
  popular?: boolean
}

export interface MarketRestaurant {
  id: string
  name: string
  slug: string
  cuisine: string
  cuisineEmoji: string
  logo: string
  banner: string // gradient tailwind classes
  bannerEmoji: string
  rating: number
  reviewCount: number
  deliveryTime: [number, number]
  deliveryFee: number
  freeFrom?: number
  distance: number
  minOrder: number
  tags: string[]
  promo?: string
  superRestaurant?: boolean
  isOpen: boolean
  description: string
  address: string
  menu: MarketDish[]
}

export interface MarketCategory {
  id: string
  name: string
  emoji: string
}

export const marketCategories: MarketCategory[] = [
  { id: 'all', name: 'Tudo', emoji: '🍽️' },
  { id: 'lanches', name: 'Lanches', emoji: '🍔' },
  { id: 'pizza', name: 'Pizza', emoji: '🍕' },
  { id: 'japonesa', name: 'Japonesa', emoji: '🍣' },
  { id: 'brasileira', name: 'Brasileira', emoji: '🍛' },
  { id: 'italiana', name: 'Italiana', emoji: '🍝' },
  { id: 'mexicana', name: 'Mexicana', emoji: '🌮' },
  { id: 'doces', name: 'Doces', emoji: '🍰' },
  { id: 'acai', name: 'Açaí', emoji: '🍇' },
  { id: 'saudavel', name: 'Saudável', emoji: '🥗' },
  { id: 'padaria', name: 'Padaria', emoji: '🥐' },
  { id: 'bebidas', name: 'Bebidas', emoji: '🍺' },
]

export const marketRestaurants: MarketRestaurant[] = [
  {
    id: 'r1',
    name: 'Burguer House',
    slug: 'burguer-house',
    cuisine: 'lanches',
    cuisineEmoji: '🍔',
    logo: '🍔',
    banner: 'from-orange-500 via-red-500 to-yellow-500',
    bannerEmoji: '🍔',
    rating: 4.8,
    reviewCount: 2841,
    deliveryTime: [25, 40],
    deliveryFee: 6.99,
    freeFrom: 60,
    distance: 1.2,
    minOrder: 25,
    tags: ['Burgers', 'Lanches', 'Americana'],
    promo: '15% OFF acima de R$ 50',
    superRestaurant: true,
    isOpen: true,
    description: 'Os melhores hambúrgueres artesanais da cidade, blend exclusivo, pão brioche fresco.',
    address: 'Av. Paulista, 1500 — Bela Vista',
    menu: [
      { id: 'r1d1', name: 'Smash Duplo Cheddar', description: '2 smashes 90g, queijo cheddar inglês duplo, picles e molho da casa no pão brioche', price: 38.90, oldPrice: 44.90, emoji: '🍔', category: 'Mais pedidos', popular: true },
      { id: 'r1d2', name: 'Bacon Angus', description: 'Blend angus 180g, bacon crocante, cheddar, cebola caramelizada, alface, tomate', price: 42.90, emoji: '🍔', category: 'Mais pedidos', popular: true },
      { id: 'r1d3', name: 'Veggie Burger', description: 'Hambúrguer de grão-de-bico, queijo vegano, rúcula, tomate seco, molho tahine', price: 34.90, emoji: '🥬', category: 'Hambúrgueres' },
      { id: 'r1d4', name: 'Chicken Crispy', description: 'Frango empanado super crocante, queijo prato, alface americana, maionese defumada', price: 32.90, emoji: '🍔', category: 'Hambúrgueres' },
      { id: 'r1d5', name: 'Onion Rings (8 un)', description: 'Anéis de cebola crocantes empanados, acompanha molho barbecue', price: 22.90, emoji: '🧅', category: 'Acompanhamentos' },
      { id: 'r1d6', name: 'Batata Frita Cheddar Bacon', description: 'Porção generosa de fritas com cheddar derretido e bacon picadinho', price: 28.90, emoji: '🍟', category: 'Acompanhamentos', popular: true },
      { id: 'r1d7', name: 'Coca-Cola 350ml', description: 'Lata gelada', price: 7.50, emoji: '🥤', category: 'Bebidas' },
      { id: 'r1d8', name: 'Cerveja IPA 600ml', description: 'Cerveja artesanal IPA gelada', price: 18.90, emoji: '🍺', category: 'Bebidas' },
      { id: 'r1d9', name: 'Milkshake Ovomaltine', description: 'Milkshake cremoso 400ml com ovomaltine crocante', price: 19.90, emoji: '🥤', category: 'Sobremesas' },
      { id: 'r1d10', name: 'Brownie com Sorvete', description: 'Brownie quente com sorvete de baunilha e calda de chocolate', price: 22.90, emoji: '🍰', category: 'Sobremesas' },
    ],
  },
  {
    id: 'r2',
    name: 'Pizza Bella Napoli',
    slug: 'pizza-bella-napoli',
    cuisine: 'pizza',
    cuisineEmoji: '🍕',
    logo: '🍕',
    banner: 'from-red-600 via-orange-500 to-yellow-400',
    bannerEmoji: '🍕',
    rating: 4.9,
    reviewCount: 4127,
    deliveryTime: [40, 55],
    deliveryFee: 0,
    distance: 2.4,
    minOrder: 35,
    tags: ['Pizza', 'Italiana', 'Massas'],
    promo: 'Frete grátis hoje!',
    superRestaurant: true,
    isOpen: true,
    description: 'Pizzas no forno a lenha, massa fermentada 48h, ingredientes importados da Itália.',
    address: 'Rua dos Pinheiros, 230 — Pinheiros',
    menu: [
      { id: 'r2d1', name: 'Margherita di Búfala', description: 'Molho de tomate San Marzano, mussarela de búfala, manjericão fresco e azeite extravirgem', price: 58.90, emoji: '🍕', category: 'Tradicionais', popular: true },
      { id: 'r2d2', name: 'Pepperoni Premium', description: 'Mussarela, pepperoni italiano fatiado fino, orégano e azeite de pimenta', price: 64.90, emoji: '🍕', category: 'Tradicionais', popular: true },
      { id: 'r2d3', name: 'Quatro Queijos', description: 'Mussarela, provolone, parmesão e gorgonzola D.O.P.', price: 68.90, emoji: '🧀', category: 'Tradicionais' },
      { id: 'r2d4', name: 'Calabresa Especial', description: 'Mussarela, calabresa artesanal, cebola roxa, azeitonas pretas e orégano', price: 56.90, emoji: '🍕', category: 'Tradicionais' },
      { id: 'r2d5', name: 'Portuguesa', description: 'Mussarela, presunto, ovos, cebola, azeitonas, ervilha e palmito', price: 62.90, emoji: '🍕', category: 'Tradicionais' },
      { id: 'r2d6', name: 'Vegetariana Rústica', description: 'Mussarela, abobrinha grelhada, berinjela, tomate seco, rúcula e parmesão', price: 59.90, emoji: '🥬', category: 'Especiais' },
      { id: 'r2d7', name: 'Carbonara di Pizza', description: 'Creme de gemas, mussarela, bacon italiano, parmesão e pimenta-do-reino', price: 71.90, emoji: '🍕', category: 'Especiais', popular: true },
      { id: 'r2d8', name: 'Doce de Nutella & Morango', description: 'Massa doce, Nutella, morangos frescos e açúcar de confeiteiro', price: 54.90, emoji: '🍫', category: 'Doces' },
      { id: 'r2d9', name: 'Coca-Cola 2L', description: 'Refrigerante 2 litros gelado', price: 14.90, emoji: '🥤', category: 'Bebidas' },
      { id: 'r2d10', name: 'Vinho Tinto Suave', description: 'Vinho tinto suave 750ml selecionado', price: 49.90, emoji: '🍷', category: 'Bebidas' },
    ],
  },
  {
    id: 'r3',
    name: 'Sushi Tokyo',
    slug: 'sushi-tokyo',
    cuisine: 'japonesa',
    cuisineEmoji: '🍣',
    logo: '🍣',
    banner: 'from-rose-500 via-pink-500 to-fuchsia-600',
    bannerEmoji: '🍣',
    rating: 4.7,
    reviewCount: 1923,
    deliveryTime: [35, 50],
    deliveryFee: 9.99,
    freeFrom: 80,
    distance: 3.1,
    minOrder: 40,
    tags: ['Japonesa', 'Sushi', 'Asiática'],
    promo: '20 peças por R$ 49,90',
    superRestaurant: true,
    isOpen: true,
    description: 'Sushi tradicional preparado por chef formado no Japão. Peixes selecionados diariamente.',
    address: 'Rua Augusta, 2100 — Jardins',
    menu: [
      { id: 'r3d1', name: 'Combo 30 peças', description: '8 nigiris, 8 hot rolls, 8 uramakis e 6 sashimis', price: 89.90, oldPrice: 109.90, emoji: '🍣', category: 'Combos', popular: true },
      { id: 'r3d2', name: 'Combo 20 peças promocional', description: '6 sashimis, 8 uramakis e 6 hot rolls — promoção do dia', price: 49.90, emoji: '🍣', category: 'Combos', popular: true },
      { id: 'r3d3', name: 'Sashimi de Salmão (10 fatias)', description: 'Fatias generosas de salmão fresco', price: 54.90, emoji: '🐟', category: 'Sashimis' },
      { id: 'r3d4', name: 'Hot Roll Philadelphia', description: 'Salmão, cream cheese e cebolinha empanado', price: 32.90, emoji: '🍣', category: 'Hot Rolls' },
      { id: 'r3d5', name: 'Uramaki Special', description: 'Salmão, abacate, cream cheese e gergelim — 8 unidades', price: 36.90, emoji: '🍣', category: 'Uramakis' },
      { id: 'r3d6', name: 'Yakisoba de Frango', description: 'Macarrão oriental refogado com frango, legumes e molho shoyu', price: 38.90, emoji: '🍜', category: 'Quentes' },
      { id: 'r3d7', name: 'Temaki de Salmão Skin', description: 'Cone de alga com pele de salmão crocante, arroz e cream cheese', price: 24.90, emoji: '🍣', category: 'Temakis' },
      { id: 'r3d8', name: 'Gyoza (6 unidades)', description: 'Pastéis japoneses recheados com porco e legumes', price: 28.90, emoji: '🥟', category: 'Entradas' },
      { id: 'r3d9', name: 'Chá Verde Gelado 500ml', description: 'Chá verde gelado natural', price: 9.90, emoji: '🍵', category: 'Bebidas' },
      { id: 'r3d10', name: 'Sake Tradicional 300ml', description: 'Saquê japonês quente ou gelado', price: 32.90, emoji: '🍶', category: 'Bebidas' },
    ],
  },
  {
    id: 'r4',
    name: 'Cantina da Nonna',
    slug: 'cantina-da-nonna',
    cuisine: 'italiana',
    cuisineEmoji: '🍝',
    logo: '🍝',
    banner: 'from-emerald-500 via-yellow-500 to-red-500',
    bannerEmoji: '🍝',
    rating: 4.6,
    reviewCount: 892,
    deliveryTime: [30, 45],
    deliveryFee: 7.99,
    distance: 1.8,
    minOrder: 30,
    tags: ['Italiana', 'Massas', 'Risotos'],
    isOpen: true,
    description: 'Receitas tradicionais da Nonna Giulia. Massas frescas feitas na hora todos os dias.',
    address: 'Alameda Lorena, 800 — Jardins',
    menu: [
      { id: 'r4d1', name: 'Spaghetti Carbonara', description: 'Espaguete com molho cremoso de gemas, parmesão, bacon e pimenta-do-reino', price: 48.90, emoji: '🍝', category: 'Massas', popular: true },
      { id: 'r4d2', name: 'Lasanha Bolonhesa', description: 'Camadas de massa fresca, ragù bolonhesa, mussarela e parmesão gratinado', price: 52.90, emoji: '🍝', category: 'Massas', popular: true },
      { id: 'r4d3', name: 'Nhoque ao Sugo', description: 'Nhoque de batata fresco com molho de tomate rústico e manjericão', price: 42.90, emoji: '🍝', category: 'Massas' },
      { id: 'r4d4', name: 'Risoto de Camarão', description: 'Risoto cremoso com camarões grelhados, limão siciliano e ervas', price: 68.90, emoji: '🦐', category: 'Risotos', popular: true },
      { id: 'r4d5', name: 'Risoto de Funghi', description: 'Risoto com mix de cogumelos selvagens e parmesão envelhecido', price: 58.90, emoji: '🍄', category: 'Risotos' },
      { id: 'r4d6', name: 'Bruschetta Caprese', description: 'Pão italiano tostado com tomate, mussarela de búfala e manjericão', price: 24.90, emoji: '🍞', category: 'Entradas' },
      { id: 'r4d7', name: 'Tiramisù', description: 'Sobremesa italiana com mascarpone, café e cacau', price: 22.90, emoji: '🍰', category: 'Sobremesas' },
      { id: 'r4d8', name: 'Vinho Chianti 750ml', description: 'Vinho tinto italiano Chianti Classico', price: 89.90, emoji: '🍷', category: 'Bebidas' },
    ],
  },
  {
    id: 'r5',
    name: 'Sabor da Roça',
    slug: 'sabor-da-roca',
    cuisine: 'brasileira',
    cuisineEmoji: '🍛',
    logo: '🍛',
    banner: 'from-amber-600 via-orange-600 to-yellow-500',
    bannerEmoji: '🍛',
    rating: 4.5,
    reviewCount: 1547,
    deliveryTime: [30, 45],
    deliveryFee: 5.99,
    distance: 0.8,
    minOrder: 25,
    tags: ['Brasileira', 'Caseira', 'PF'],
    promo: 'Marmita do dia R$ 24,90',
    isOpen: true,
    description: 'Comida caseira como da vovó. Pratos do dia, marmitas executivas e feijoada aos sábados.',
    address: 'Rua dos Coqueiros, 45 — Vila Madalena',
    menu: [
      { id: 'r5d1', name: 'Feijoada Completa Individual', description: 'Feijoada tradicional com arroz, couve refogada, farofa, laranja e torresmo', price: 39.90, emoji: '🍛', category: 'Pratos do dia', popular: true },
      { id: 'r5d2', name: 'Picanha na Chapa', description: 'Picanha grelhada, arroz, feijão tropeiro, vinagrete e fritas', price: 52.90, emoji: '🥩', category: 'Pratos principais', popular: true },
      { id: 'r5d3', name: 'Frango à Parmegiana', description: 'Filé de frango empanado, molho de tomate, mussarela, arroz e fritas', price: 38.90, emoji: '🍗', category: 'Pratos principais' },
      { id: 'r5d4', name: 'Marmita Executiva', description: 'Arroz, feijão, bife acebolado, salada e fritas. Promoção do dia', price: 24.90, emoji: '🍱', category: 'Marmitas', popular: true },
      { id: 'r5d5', name: 'Marmita Vegetariana', description: 'Arroz integral, feijão, omelete de queijo, abobrinha e salada colorida', price: 22.90, emoji: '🍱', category: 'Marmitas' },
      { id: 'r5d6', name: 'Strogonoff de Frango', description: 'Strogonoff cremoso com arroz, batata palha e salada', price: 32.90, emoji: '🍗', category: 'Pratos principais' },
      { id: 'r5d7', name: 'Coxinha (3 un)', description: 'Coxinha de frango com catupiry, frita na hora', price: 14.90, emoji: '🥟', category: 'Salgados' },
      { id: 'r5d8', name: 'Suco de Laranja Natural 500ml', description: 'Suco natural feito na hora', price: 9.90, emoji: '🍊', category: 'Bebidas' },
    ],
  },
  {
    id: 'r6',
    name: 'Taqueria El Diablo',
    slug: 'taqueria-el-diablo',
    cuisine: 'mexicana',
    cuisineEmoji: '🌮',
    logo: '🌮',
    banner: 'from-red-600 via-orange-500 to-yellow-500',
    bannerEmoji: '🌮',
    rating: 4.7,
    reviewCount: 1284,
    deliveryTime: [30, 45],
    deliveryFee: 7.99,
    distance: 2.0,
    minOrder: 30,
    tags: ['Mexicana', 'Tex-Mex', 'Picante'],
    promo: 'Combo nachos + drink R$ 39,90',
    isOpen: true,
    description: 'Tacos, burritos e nachos autênticos. Tortillas frescas feitas na casa, tequila gelada.',
    address: 'Rua Aspicuelta, 350 — Vila Madalena',
    menu: [
      { id: 'r6d1', name: 'Taco al Pastor (3 un)', description: 'Tortilla de milho, carne suína marinada, abacaxi grelhado, cebola e coentro', price: 32.90, emoji: '🌮', category: 'Tacos', popular: true },
      { id: 'r6d2', name: 'Burrito Carne', description: 'Tortilla recheada com carne, arroz mexicano, feijão, queijo e guacamole', price: 38.90, emoji: '🌯', category: 'Burritos', popular: true },
      { id: 'r6d3', name: 'Nachos Supreme', description: 'Tortilla chips, queijo derretido, jalapeños, guacamole, sour cream e pico de gallo', price: 36.90, emoji: '🧀', category: 'Petiscos', popular: true },
      { id: 'r6d4', name: 'Quesadilla de Frango', description: 'Tortilla recheada com frango desfiado, queijo, pimentões e cebola caramelizada', price: 32.90, emoji: '🫓', category: 'Quesadillas' },
      { id: 'r6d5', name: 'Chili con Carne', description: 'Carne moída com feijão vermelho, pimentas e tortilhas crocantes', price: 34.90, emoji: '🌶️', category: 'Pratos' },
      { id: 'r6d6', name: 'Guacamole + Chips', description: 'Guacamole fresco preparado na hora com chips de tortilla', price: 24.90, emoji: '🥑', category: 'Entradas' },
      { id: 'r6d7', name: 'Margarita Clássica', description: 'Tequila, triple sec, limão e sal na borda', price: 22.90, emoji: '🍹', category: 'Drinks' },
      { id: 'r6d8', name: 'Cerveja Corona', description: 'Cerveja Corona Extra com limão', price: 14.90, emoji: '🍺', category: 'Bebidas' },
    ],
  },
  {
    id: 'r7',
    name: 'Doceria Cacau',
    slug: 'doceria-cacau',
    cuisine: 'doces',
    cuisineEmoji: '🍰',
    logo: '🍰',
    banner: 'from-pink-400 via-rose-500 to-fuchsia-600',
    bannerEmoji: '🍰',
    rating: 4.9,
    reviewCount: 3421,
    deliveryTime: [20, 35],
    deliveryFee: 5.99,
    freeFrom: 50,
    distance: 1.5,
    minOrder: 20,
    tags: ['Doces', 'Bolos', 'Sobremesas'],
    promo: 'Brigadeiro a R$ 3,50',
    superRestaurant: true,
    isOpen: true,
    description: 'Bolos, tortas, brigadeiros gourmet e sobremesas artesanais. Confeitaria fina.',
    address: 'Rua Oscar Freire, 920 — Jardins',
    menu: [
      { id: 'r7d1', name: 'Bolo de Chocolate Trufado', description: 'Bolo de chocolate belga com recheio cremoso e ganache — fatia individual', price: 18.90, emoji: '🎂', category: 'Bolos', popular: true },
      { id: 'r7d2', name: 'Brigadeiro Gourmet (caixa 9 un)', description: 'Caixa com 9 brigadeiros gourmet variados', price: 31.50, oldPrice: 36.90, emoji: '🍫', category: 'Doces', popular: true },
      { id: 'r7d3', name: 'Cheesecake Frutas Vermelhas', description: 'Cheesecake cremoso com calda de frutas vermelhas — fatia', price: 22.90, emoji: '🍰', category: 'Tortas' },
      { id: 'r7d4', name: 'Pavê de Maracujá', description: 'Pavê tradicional com mousse de maracujá — porção 250g', price: 19.90, emoji: '🍮', category: 'Sobremesas' },
      { id: 'r7d5', name: 'Torta de Limão', description: 'Massa amanteigada, recheio de limão e merengue maçaricado', price: 21.90, emoji: '🥧', category: 'Tortas', popular: true },
      { id: 'r7d6', name: 'Cookies (6 un)', description: 'Cookies caseiros com gotas de chocolate belga', price: 24.90, emoji: '🍪', category: 'Doces' },
      { id: 'r7d7', name: 'Macarons (caixa 6 un)', description: 'Macarons franceses sortidos', price: 38.90, emoji: '🍪', category: 'Doces' },
      { id: 'r7d8', name: 'Café Espresso', description: 'Café espresso premium 50ml', price: 7.50, emoji: '☕', category: 'Bebidas' },
    ],
  },
  {
    id: 'r8',
    name: 'Açaí da Praia',
    slug: 'acai-da-praia',
    cuisine: 'acai',
    cuisineEmoji: '🍇',
    logo: '🍇',
    banner: 'from-purple-600 via-fuchsia-500 to-pink-500',
    bannerEmoji: '🍇',
    rating: 4.6,
    reviewCount: 2103,
    deliveryTime: [20, 35],
    deliveryFee: 4.99,
    distance: 0.6,
    minOrder: 18,
    tags: ['Açaí', 'Sorvetes', 'Smoothies'],
    promo: '500ml com 3 acompanhamentos',
    isOpen: true,
    description: 'Açaí cremoso direto do Pará, sorvetes, smoothies e tigelas montadas a gosto.',
    address: 'Av. Brigadeiro, 700 — Itaim',
    menu: [
      { id: 'r8d1', name: 'Açaí 500ml + 3 acompanhamentos', description: 'Açaí cremoso 500ml com 3 acompanhamentos a sua escolha (granola, leite condensado, banana, morango...)', price: 22.90, emoji: '🍇', category: 'Açaís', popular: true },
      { id: 'r8d2', name: 'Açaí 700ml + 5 acompanhamentos', description: 'Açaí 700ml com 5 acompanhamentos a sua escolha', price: 32.90, emoji: '🍇', category: 'Açaís', popular: true },
      { id: 'r8d3', name: 'Açaí Família 1L', description: 'Açaí 1 litro com 6 acompanhamentos a sua escolha', price: 44.90, emoji: '🍇', category: 'Açaís' },
      { id: 'r8d4', name: 'Smoothie de Morango', description: 'Smoothie cremoso de morango com iogurte natural', price: 14.90, emoji: '🍓', category: 'Smoothies' },
      { id: 'r8d5', name: 'Vitamina de Banana', description: 'Vitamina cremosa de banana com aveia e mel', price: 12.90, emoji: '🍌', category: 'Smoothies' },
      { id: 'r8d6', name: 'Sorvete 2 bolas', description: 'Duas bolas de sorvete cremoso a sua escolha', price: 14.90, emoji: '🍦', category: 'Sorvetes' },
      { id: 'r8d7', name: 'Tapioca de Frango', description: 'Tapioca recheada com frango desfiado e catupiry', price: 18.90, emoji: '🫓', category: 'Salgados' },
      { id: 'r8d8', name: 'Suco Detox', description: 'Couve, limão, maçã e gengibre 500ml', price: 13.90, emoji: '🥤', category: 'Sucos' },
    ],
  },
  {
    id: 'r9',
    name: 'Green Bowl',
    slug: 'green-bowl',
    cuisine: 'saudavel',
    cuisineEmoji: '🥗',
    logo: '🥗',
    banner: 'from-emerald-400 via-green-500 to-lime-500',
    bannerEmoji: '🥗',
    rating: 4.8,
    reviewCount: 1102,
    deliveryTime: [25, 40],
    deliveryFee: 6.99,
    distance: 1.4,
    minOrder: 28,
    tags: ['Saudável', 'Saladas', 'Fit'],
    isOpen: true,
    description: 'Comida fitness, low carb, vegana e funcional. Pratos balanceados por nutricionista.',
    address: 'Rua Bandeira Paulista, 412 — Itaim',
    menu: [
      { id: 'r9d1', name: 'Bowl Frango Grelhado', description: 'Quinoa, frango grelhado, abacate, tomate cereja, ovo cozido, mix de folhas', price: 38.90, emoji: '🥗', category: 'Bowls', popular: true },
      { id: 'r9d2', name: 'Bowl Salmão Teriyaki', description: 'Arroz integral, salmão grelhado teriyaki, edamame, manga, gergelim', price: 52.90, emoji: '🥗', category: 'Bowls', popular: true },
      { id: 'r9d3', name: 'Bowl Vegano', description: 'Quinoa, grão-de-bico crocante, batata-doce, abacate, kale, tahine', price: 36.90, emoji: '🥗', category: 'Bowls' },
      { id: 'r9d4', name: 'Salada Caesar Frango', description: 'Alface americana, frango grelhado, croutons integrais, parmesão, molho caesar', price: 32.90, emoji: '🥗', category: 'Saladas' },
      { id: 'r9d5', name: 'Wrap de Atum', description: 'Wrap integral com atum, abacate, alface e tomate', price: 28.90, emoji: '🌯', category: 'Wraps' },
      { id: 'r9d6', name: 'Sopa Detox', description: 'Sopa de legumes com proteína vegetal', price: 22.90, emoji: '🍲', category: 'Sopas' },
      { id: 'r9d7', name: 'Suco Verde Detox', description: 'Couve, limão, gengibre, maçã e hortelã', price: 14.90, emoji: '🥤', category: 'Bebidas' },
      { id: 'r9d8', name: 'Água de Coco 500ml', description: 'Água de coco natural gelada', price: 9.90, emoji: '🥥', category: 'Bebidas' },
    ],
  },
  {
    id: 'r10',
    name: 'Padaria Pão Quente',
    slug: 'padaria-pao-quente',
    cuisine: 'padaria',
    cuisineEmoji: '🥐',
    logo: '🥐',
    banner: 'from-yellow-500 via-amber-500 to-orange-500',
    bannerEmoji: '🥖',
    rating: 4.4,
    reviewCount: 678,
    deliveryTime: [15, 25],
    deliveryFee: 4.99,
    distance: 0.4,
    minOrder: 15,
    tags: ['Padaria', 'Café', 'Salgados'],
    isOpen: true,
    description: 'Padaria tradicional. Pão quente saindo do forno, salgados frescos e cafés especiais.',
    address: 'Rua Cardeal Arcoverde, 120 — Pinheiros',
    menu: [
      { id: 'r10d1', name: 'Combo Café da Manhã', description: 'Café com leite, pão na chapa com manteiga, ovo mexido e suco de laranja', price: 18.90, emoji: '🥐', category: 'Café da manhã', popular: true },
      { id: 'r10d2', name: 'Pão Francês (kg)', description: 'Pão francês fresquinho saindo do forno (aprox. 14 unidades)', price: 16.90, emoji: '🥖', category: 'Pães' },
      { id: 'r10d3', name: 'Croissant de Manteiga', description: 'Croissant folhado de manteiga francesa', price: 8.90, emoji: '🥐', category: 'Pães', popular: true },
      { id: 'r10d4', name: 'Pão de Queijo (6 un)', description: 'Pão de queijo mineiro tradicional, quentinho', price: 16.90, emoji: '🧀', category: 'Salgados', popular: true },
      { id: 'r10d5', name: 'Esfiha de Carne (4 un)', description: 'Esfihas abertas de carne temperada', price: 19.90, emoji: '🥟', category: 'Salgados' },
      { id: 'r10d6', name: 'Mini Pizza (4 un)', description: 'Mini pizzas variadas: muçarela, calabresa, frango e portuguesa', price: 22.90, emoji: '🍕', category: 'Salgados' },
      { id: 'r10d7', name: 'Sonho de Doce de Leite', description: 'Sonho recheado com doce de leite e açúcar', price: 7.50, emoji: '🍩', category: 'Doces' },
      { id: 'r10d8', name: 'Cappuccino', description: 'Cappuccino cremoso com canela', price: 9.90, emoji: '☕', category: 'Bebidas' },
    ],
  },
  {
    id: 'r11',
    name: 'Empório das Cervejas',
    slug: 'emporio-cervejas',
    cuisine: 'bebidas',
    cuisineEmoji: '🍺',
    logo: '🍺',
    banner: 'from-amber-600 via-yellow-600 to-orange-600',
    bannerEmoji: '🍻',
    rating: 4.7,
    reviewCount: 945,
    deliveryTime: [25, 40],
    deliveryFee: 7.99,
    distance: 1.9,
    minOrder: 35,
    tags: ['Bebidas', 'Cervejas', 'Drinks'],
    promo: 'Fardo de cerveja R$ 89,90',
    isOpen: true,
    description: 'Cervejas artesanais, importadas e nacionais. Vinhos selecionados e drinks prontos.',
    address: 'Rua Wisard, 280 — Vila Madalena',
    menu: [
      { id: 'r11d1', name: 'Fardo Heineken (12 un)', description: '12 long necks Heineken 330ml geladas', price: 89.90, oldPrice: 105.90, emoji: '🍺', category: 'Cervejas', popular: true },
      { id: 'r11d2', name: 'Cerveja IPA Artesanal 600ml', description: 'IPA artesanal local lupulada', price: 22.90, emoji: '🍺', category: 'Cervejas', popular: true },
      { id: 'r11d3', name: 'Stella Artois 600ml', description: 'Stella Artois 600ml gelada', price: 16.90, emoji: '🍺', category: 'Cervejas' },
      { id: 'r11d4', name: 'Vinho Tinto Reservado 750ml', description: 'Vinho tinto chileno selecionado', price: 79.90, emoji: '🍷', category: 'Vinhos' },
      { id: 'r11d5', name: 'Gin Tônica Pronto 500ml', description: 'Drink gin tônica pronto, gelado', price: 32.90, emoji: '🍹', category: 'Drinks' },
      { id: 'r11d6', name: 'Caipirinha de Limão 500ml', description: 'Caipirinha tradicional pronta gelada', price: 24.90, emoji: '🍹', category: 'Drinks' },
      { id: 'r11d7', name: 'Whisky Jack Daniels 1L', description: 'Whisky americano Jack Daniels Old No.7', price: 189.90, emoji: '🥃', category: 'Destilados' },
      { id: 'r11d8', name: 'Gelo (5kg)', description: 'Saco de gelo cristal 5kg', price: 14.90, emoji: '🧊', category: 'Acompanhamentos' },
    ],
  },
  {
    id: 'r12',
    name: 'Veggie Burger Co.',
    slug: 'veggie-burger-co',
    cuisine: 'lanches',
    cuisineEmoji: '🌱',
    logo: '🌱',
    banner: 'from-green-500 via-emerald-500 to-teal-500',
    bannerEmoji: '🌱',
    rating: 4.5,
    reviewCount: 412,
    deliveryTime: [30, 45],
    deliveryFee: 6.99,
    distance: 2.6,
    minOrder: 30,
    tags: ['Vegano', 'Vegetariano', 'Lanches'],
    isOpen: false,
    description: '100% vegetal. Hambúrgueres plant-based, opções veganas e sem glúten.',
    address: 'Rua Harmonia, 540 — Vila Madalena',
    menu: [
      { id: 'r12d1', name: 'Beyond Burger', description: 'Hambúrguer plant-based Beyond Meat, queijo vegano, alface e tomate', price: 42.90, emoji: '🌱', category: 'Hambúrgueres', popular: true },
      { id: 'r12d2', name: 'Veggie Bacon', description: 'Hambúrguer de feijão preto, bacon vegetal, queijo cheddar vegano', price: 38.90, emoji: '🌱', category: 'Hambúrgueres' },
      { id: 'r12d3', name: 'Falafel Burger', description: 'Hambúrguer de falafel, tahine, alface, tomate, pão integral', price: 34.90, emoji: '🌱', category: 'Hambúrgueres' },
      { id: 'r12d4', name: 'Batata Doce Frita', description: 'Batata doce em palitos, fritas crocantes', price: 22.90, emoji: '🍠', category: 'Acompanhamentos' },
      { id: 'r12d5', name: 'Onion Rings Veganos', description: 'Anéis de cebola empanados veganos', price: 19.90, emoji: '🧅', category: 'Acompanhamentos' },
      { id: 'r12d6', name: 'Refri Natural Limão', description: 'Refrigerante natural sem açúcar', price: 9.90, emoji: '🥤', category: 'Bebidas' },
    ],
  },
]

export function getRestaurantById(id: string): MarketRestaurant | undefined {
  return marketRestaurants.find(r => r.id === id)
}

export function getRestaurantBySlug(slug: string): MarketRestaurant | undefined {
  return marketRestaurants.find(r => r.slug === slug)
}

export function getDishById(restaurantId: string, dishId: string): MarketDish | undefined {
  return getRestaurantById(restaurantId)?.menu.find(d => d.id === dishId)
}
